### ISSUE TITLE
The file /dev/sda1 does not exist and no size was specified.

### ISSUE THREAD

**Issue by smartroad** [adafruit/Adafruit-Pi-ExternalRoot-Helper#5]
Hi!

Tried to run this using Jessie-lite and ended up with:

```
sudo ./adafruit-pi-externalroot-helper -d /dev/sda
Target drive = /dev/sda
[start] Will create new ext4 filesystem on /dev/sda
[start] If there is data on /dev/sda, it will be lost.
Really proceed? (y)es / (n)o y
[dependencies] Installing gdisk, rsync, and parted.
Reading package lists... Done
Building dependency tree
Reading state information... Done
gdisk is already the newest version.
parted is already the newest version.
rsync is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
[fs create] Creating /dev/sda1
[fs create] Creating ext4 filesystem on /dev/sda1
mke2fs 1.42.12 (29-Aug-2014)
The file /dev/sda1 does not exist and no size was specified.
```
yet if I run mke2fs /dev/sda1 it formats the drive no issue

**Comment by skilbjo** [comment]
+1

**Comment by rpiuser314** [comment]
I have had this problem myself.  I found that manually entering the command: "sudo mkfs -t ext4 -L rootfs /dev/sda1" (w/o quotes)  worked just fine.  I figured that perhaps the script was running faster
than the file /dev/sda1 was able to be seen.  I solved the problem by adding a statement of "sleep 1" (w/o quotes) just before the mkfs ...  line.  Make that addition and run the script again.
Good luck!

**Comment by cartpauj** [comment]
Also ran into this myself, cloned the repo locally and modified the script with "sleep 1" as @rpiuser314 mentioned. Worked like a charm!
+1

**Comment by aronayne** [comment]
Appears to be a common issue, fix suggested by @rpiuser314 fixed it for me on Raspberry PI with Jesse. Fix should be committed to master ?

**Comment by emirpprime** [comment]
**+1**
Also fixed by @rpiuser314

**Comment by marqxb** [comment]
+1
Thanks @rpiuser314

**Comment by IgorGanapolsky** [comment]
I still get the error:
**The file /dev/sda1 does not exist and no size was specified**
despite the fix suggested in this thread...

**Comment by diostam** [comment]
The sleep 1 trick did the job. thanks

**Comment by 2475810** [comment]
sleep 1 trick didn't do it for me
got around this by first run:
"sudo mkfs -t ext4 /dev/sda1", then comment out this line from the script "mkfs -t ext4 -L rootfs "${target_partition}", after this the script runs without any issues.

**Comment by cryptomonk** [comment]
+1 
@rpiuser314
(Open **adafruit-pi-externalroot-helper** with a text editor)  `nano adafruit-pi-externalroot-helper` 

Then see this: [https://github.com/adafruit/Adafruit-Pi-ExternalRoot-Helper/pull/8/files](https://github.com/adafruit/Adafruit-Pi-ExternalRoot-Helper/pull/8/files)

:)

**Comment by remrol** [comment]
Thank you, sleep 1 solves the problem for me

**Comment by JPM-git** [comment]
same here
sleep 1
solves the problem.

Thank you

**Comment by vmstan** [comment]
There is now a sleep 5 in the published code.

**Comment by rpiuser314** [comment]
Hi Michael,

Thank you for the update.  That is good to hear that that the sleep is now
in the code.
It is kind of a big hammer approach, but I didn't know any other way to fix
my problem.
Thank you again.

Sincerely,
Kedric Bartsch
